### ISSUE TITLE
Error updating spiffs

### ISSUE THREAD

**Issue by ulinieto** [alidonet/gc97_esp#1] opened 2021-08-19 23:21 UTC
Hello, im trying to use your software. I charge the First bin, acces to web Server 192.168.4.1, but when I try to update spiffs, i get the no file error. What can i do to solve it?? Thanks in advance.

**Comment by alidonet** [comment] 2021-08-20 08:23
I think, you can try to setup the credentials for your WiFi network at first and after that try to upload file via OTA.
Also, you can try to use Arduino IDE (or any other similar software) and try to upload that file via "Sketch data upload" command.

**Comment by ulinieto** [comment] 2021-08-20 11:55
I've tried to set youth WiFi credentials and doesn't work. I'm gonna tried to upload the spiff the way you say. Thanks

**Comment by alidonet** [comment] 2021-08-20 12:12
I'll try to reproduce your issue with upload spiff.
Can you describe, shortly, what is the issue with setup WiFi? Screenshots or event short video will be very good.

**Comment by ulinieto** [comment] 2021-08-20 12:26
Hello, i've tried to upload the spiffs via sketch but no success. When i triy to set up te credentials of my wifi no success.

![Captura](https://user-images.githubusercontent.com/61251245/130232744-95b77e9e-54db-4a17-95c2-1a810f2a3c12.PNG)

**Comment by ulinieto** [comment] 2021-08-20 12:29
First i uplod "GC97_ESP.ino". After the upload i see de ap of the esp. I can access to the minimal web but i can't do nothing. 
![Captura](https://user-images.githubusercontent.com/61251245/130233280-038447b6-4e58-4a25-b280-9381b8ff0f3e.PNG)

**Comment by alidonet** [comment] 2021-08-20 15:11
Did you try to upload the https://github.com/alidonet/GC97_ESP/blob/main/GC97_ESP.spiffs.bin via upgrade form? With a default settings it will be http://192.168.4.1/update

**Comment by alidonet** [comment] 2021-08-20 16:13
Yes, the issue is reproduced. Will try to find a workaround.

**Comment by alidonet** [comment] 2021-08-20 18:53
Just uploaded the new version of the major GC97_ESP.ino.bin. Please update your ESP and try again.
You can use the hard reset cmd to erase/restore the default settings via call http://192.168.4.1/cmd/reset
Also you can track the ESP state/debug output via COM monitor.

**Comment by ulinieto** [comment] 2021-08-20 19:44
Thanks, now it work. Tomorrow i'll connect de GC97.

**Comment by ulinieto** [comment] 2021-08-20 21:37
Are there any possibility getting the password of the sources??

**Comment by ulinieto** [comment] 2021-08-24 20:43
I.m sorry but i'm really  interested in your sofware and i need to be sure that you haven't included malware and if you don't give access to your work i can't be sure is free of malware.

Thanks in advance.

**Comment by alidonet** [comment] 2021-08-25 17:36
I understood. But at the same time I can tell that ESP is not so good platform for malware and I did it for myself at first. You can sniff the traffic and check how it works. Sorry, I don't want to share my sources, at least for now.

**Comment by alidonet** [comment] 2023-04-17 21:29
Sorry for delay with answer :)
Fixed in 230415. When upload via Arduino IDE you are specifying the wrong memory allocation.
Now you can upload a single file or use http://<ip_address>/upload page and flash the .spiff.bin file on the second row option.

**Closed as completed by alidonet** 2023-04-17 21:29 UTC
